### ISSUE TITLE
Quest - Mislabelling of questionnaire responses

### ISSUE THREAD

**Issue by ekigamba** [opensrp/fhircore#737]
**Describe the bug**
Multiple MSF questionnaires are mislabelled as G6PD

**To Reproduce**
1. Go to 'Harry Porter'
2. Click on either of the 'G6PD Test Results (09 Nov 2021)' responses. They open the MSF questionnaire and appropriate QR

**Expected behavior**
The labelling should clearly indicate the parent Questionnaire

**Screenshots**
![Screenshot from 2021-11-10 15-27-02](https://user-images.githubusercontent.com/31766075/141113035-d7b9e12a-5035-414c-8d12-0b6327f41189.png)

![Screenshot from 2021-11-10 15-27-18](https://user-images.githubusercontent.com/31766075/141113026-dddd7f0c-cbaf-4b08-b375-4d7883afe12f.png)

**Smartphone (please complete the following information):**
 - Device: Nexus 5X emulator
 - Android version: API 28
 - Build number: [e.g. Settings -> About phone -> Build number]
 - Version [e.g. 24]

**Additional context**

**Comment by pld** [comment]
This sounds like a general problem w/Quest, is that correct?

**Comment by shoaibmushtaq25** [comment]
Hey @f-odhiambo , What should be the expected labelling here? which are the labels we wanna change here and whats the new labels? or any other additional context on this issue that might be helpful.

**Comment by f-odhiambo** [comment]
@shoaibmushtaq25 the issue here is that when you open a preciously completed survey for MSF as an example the correponding QR is for G6PD and vice versa . Thus the expected behavior should be once I complete a MSF or G6PD survey I should be able to retrieve the corresponding QR based on name and date

**Comment by shoaibmushtaq25** [comment]
While working on this issue, I came across a different issue "Multiple entries of same Questionnaire Response were showing in the Responses section", I fixed this multiple entries of same Questionnaire Response issue. Should we track it as a separate issue or we are ok with it not creating a separate one. cc: @f-odhiambo 

For the mis-labelling of QuestionnaireResponses, I debugged the different parts of the flow, 

1. Show the QuestionnaireResponse on the screen
2. Save the QuestionnaireResponse upon filling the form
3. Syncing the Resources(QR for our case) to the server

So now I have figured it out that the issue is in Point 3 (Syncing the resources), Now I am going to do more deep debugging of sync flow to understand and fix the problem.

**Comment by f-odhiambo** [comment]
@shoaibmushtaq25 Let's track it on this same ticket and then update the details in the PR and change log to track what has been fixed

**Comment by shoaibmushtaq25** [comment]
sure, Thanks.

**Comment by shoaibmushtaq25** [comment]
I did debugging to check if there is an issue on saving QuestionnaireResponse data into FHIR Engine, also debugged sync flow but so far I found out that the local fhir engine copy upon saving QuestionnaireResponse is showing the correct labels but as we upload it via Sync, the server db shows the changes label on the server and upon next syncing into app, app downloads the changed labelled and show the in-correct ones. so it looks like there is some issue on server side, may be someone from BE side can better comment on this and please advise what should I do next on this? cc: @dubdabasoduba @f-odhiambo 
Note: Local(fhir engine copy) and Server copy is attached below.

**Local Snapshot (FHIR Engine copy):*
`{"resourceType":"QuestionnaireResponse","id":"57d43921-00f1-4bba-bde0-6ee09d351b1b","meta":{"tag":[{"system":"http://fhir.ona.io","code":"000002","display":"MSF Questionnaire"}]},"questionnaire":"Questionnaire/3748","subject":{"reference":"Patient/e91f12be-6c54-46c0-87c9-09103c24f782"},"authored":"2021-12-07T16:16:55+05:00","item":[{"linkId":"8b06c86a-9d44-403a-861a-7afbebfad307","answer":[{"valueCoding":{"id":"b983e2ee-7169-42cd-ca46-2b77299b7064","system":"urn:uuid:435ea5e2-4fcc-4f13-b254-674ca84998a7","code":"responsive-","display":"Responsive "},"item":[{"linkId":"3e1cd435-2fc7-4584-9472-a75f53d731cb","answer":[{"valueCoding":{"id":"3082f1ea-eafa-4000-8807-9a85bc122a1d","system":"urn:uuid:e567be82-ba8f-4587-db09-142fff84e07b","code":"no","display":"No"},"item":[{"linkId":"f231e2db-ff64-48a6-88d3-15509870abc5","answer":[{"valueCoding":{"id":"f92718ec-a7f0-428e-bf1d-0b41ff9950cd","system":"urn:uuid:26bbc99d-9488-4a77-fb12-12aed8d6f477","code":"yes","display":"Yes"},"item":[{"linkId":"b96ecf71-b1ff-4964-8423-801b53d9b48c"}]}]}]}]}]}]}]}`

**Server Snapshot(After Sync):**
`{
  "resourceType": "QuestionnaireResponse",
  "id": "57d43921-00f1-4bba-bde0-6ee09d351b1b",
  "meta": {
    "versionId": "1",
    "lastUpdated": "2021-12-07T11:35:45.225+00:00",
    "source": "#ad116131348b6c89",
    "tag": [ {
      "system": "http://fhir.ona.io",
      "code": "000002",
      "display": "G6PD Test Results"
    } ]
  },
  "questionnaire": "Questionnaire/3748",
  "subject": {
    "reference": "Patient/e91f12be-6c54-46c0-87c9-09103c24f782"
  },
  "authored": "2021-12-07T16:16:55+05:00",
  "item": [ {
    "linkId": "8b06c86a-9d44-403a-861a-7afbebfad307",
    "answer": [ {
      "valueCoding": {
        "id": "b983e2ee-7169-42cd-ca46-2b77299b7064",
        "system": "urn:uuid:435ea5e2-4fcc-4f13-b254-674ca84998a7",
        "code": "responsive-",
        "display": "Responsive "
      },
      "item": [ {
        "linkId": "3e1cd435-2fc7-4584-9472-a75f53d731cb",
        "answer": [ {
          "valueCoding": {
            "id": "3082f1ea-eafa-4000-8807-9a85bc122a1d",
            "system": "urn:uuid:e567be82-ba8f-4587-db09-142fff84e07b",
            "code": "no",
            "display": "No"
          },
          "item": [ {
            "linkId": "f231e2db-ff64-48a6-88d3-15509870abc5",
            "answer": [ {
              "valueCoding": {
                "id": "f92718ec-a7f0-428e-bf1d-0b41ff9950cd",
                "system": "urn:uuid:26bbc99d-9488-4a77-fb12-12aed8d6f477",
                "code": "yes",
                "display": "Yes"
              },
              "item": [ {
                "linkId": "b96ecf71-b1ff-4964-8423-801b53d9b48c"
              } ]
            } ]
          } ]
        } ]
      } ]
    } ]
  } ]
}`

**Comment by ekigamba** [comment]
@shoaibmushtaq25 I would rule out the server changing the label. I just checked the server and the corresponding questionnaire has the same label

1. I think the code has been previously used in another questionnaire -> Questionnaire/4433. I think this could be causing the rewrite of the display value.

### How to test
1. Can you try manually pushing a different `QuestionnaireResponse` referencing the same `Questionnaire` and see if the display changes? Use postman for this. This might point to our implementation introducing the bug
2. If not, see if updating the code to an unused code like `000003` will solve the issue. Also check documentation and update us on how to correctly do this

**Comment by shoaibmushtaq25** [comment]
I tried different use cases (using POSTMAN) to update the `QuestionnaireResponse` and `MSF Questionnaire` itself. 
**Here are those with `QuetionnaireResponse`,** 

1. I updated the `QuestionnaireResponse` (id = 57d43921-00f1-4bba-bde0-6ee09d351b1b) with some different `display` value (New MSF Questionnaire) with same `meta.tag.code` (000002) but the issue still persists(server changes the value to (G6PD Test Results) as per the code(000002), looks like it’s tied to code. 
2. I updated the `QuestionnaireResponse` (id = 57d43921-00f1-4bba-bde0-6ee09d351b1b) with a different `meta.tag.code` (000003) and the same display value(MSF Questionnaire), then upon fetching this `QuestionniareResponse` the server returns the `display` as "G6PD Patient".
3. I updated the `QuestionnaireResponse` (id = 57d43921-00f1-4bba-bde0-6ee09d351b1b) with a different `meta.tag.code` (000004) assuming that this code is not already in use and the `display` value as "A New MSF Questionnaire", the upon fetching this `QuestionnaireResponse`, the server returns the `QuestionnaireResponse` with the same `code` (000004) and same `display` (A New MSF Questionnaire) as we passed in the request body.
`{
    "resourceType": "QuestionnaireResponse",
    "id": "57d43921-00f1-4bba-bde0-6ee09d351b1b",
    "meta": {
        "versionId": "3",
        "lastUpdated": "2021-12-09T07:37:55.481+00:00",
        "source": "#5c7875e18dc23f3a",
        "tag": [
            {
                "system": "http://fhir.ona.io",
                "code": "000003",
                "display": "G6PD Patient"
            },
            {
                "system": "http://fhir.ona.io",
                "code": "000002",
                "display": "G6PD Test Results"
            },
            {
                "system": "http://fhir.ona.io",
                "code": "000004",
                "display": "A New MSF Questionniare"
            }
        ]
    },
    "questionnaire": "Questionnaire/3748",
    "subject": {
        "reference": "Patient/e91f12be-6c54-46c0-87c9-09103c24f782"
    },
    "authored": "2021-12-07T16:16:55+05:00",
    "item": [
        {
            "linkId": "8b06c86a-9d44-403a-861a-7afbebfad307",
            "answer": [
                {
                    "valueCoding": {
                        "id": "b983e2ee-7169-42cd-ca46-2b77299b7064",
                        "system": "urn:uuid:435ea5e2-4fcc-4f13-b254-674ca84998a7",
                        "code": "responsive-",
                        "display": "Responsive "
                    },
                    "item": [
                        {
                            "linkId": "3e1cd435-2fc7-4584-9472-a75f53d731cb",
                            "answer": [
                                {
                                    "valueCoding": {
                                        "id": "3082f1ea-eafa-4000-8807-9a85bc122a1d",
                                        "system": "urn:uuid:e567be82-ba8f-4587-db09-142fff84e07b",
                                        "code": "no",
                                        "display": "No"
                                    },
                                    "item": [
                                        {
                                            "linkId": "f231e2db-ff64-48a6-88d3-15509870abc5",
                                            "answer": [
                                                {
                                                    "valueCoding": {
                                                        "id": "f92718ec-a7f0-428e-bf1d-0b41ff9950cd",
                                                        "system": "urn:uuid:26bbc99d-9488-4a77-fb12-12aed8d6f477",
                                                        "code": "yes",
                                                        "display": "Yes"
                                                    },
                                                    "item": [
                                                        {
                                                            "linkId": "b96ecf71-b1ff-4964-8423-801b53d9b48c"
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}`

**Here are those that I performed with `Questionnaire`,**
1. I updated the `MSF Questionnaire` (id = 3748) with a different `meta.tag.code` (000004) and checked the impact on the QuestPatientDetailsScreen UI , the `MSF Questionnaire` (id = 3748) is no more visible on the screen, the reason is we are only fetching the `Questionnaire forms` with the `code` (000002) to display it on this screen, as per the [profile_config.json file](https://github.com/opensrp/fhircore/blob/f85bbb5565c1125c7bb8f29a0885f5b75f187cca/android/quest/src/main/assets/configurations/form/profile_config.json#L5)

**Summary:**
upon changing the code in the Questionniare, the server returns the correct display but we are fetching forms with only code(000002) to display it on the QuestPatientDetail screen,
so what we can do here as next steps to fix the problem? Do we change the `profile_config.json` to include the code of `MSF Quetsionniare` (000004) as well or is there any other way to resolve this? cc: @ekigamba @f-odhiambo

**Comment by shoaibmushtaq25** [comment]
I had a call with @maimoonak on this while Kenya team was off/Company retreat and discuss the different scenarios mentioned [here](https://github.com/opensrp/fhircore/issues/737#issuecomment-990703250) , She suggested me to use the name/title of questionnaire which is attached to a particular QuestionnaireResponse. I implemented the solution this way and opened a [PR](https://github.com/opensrp/fhircore/pull/863) for this. 

Moreover, I came across a different issue, the app crashes when we open G6PD Test Photo Result QuestionnaireResponse. I created a [separate issue](https://github.com/opensrp/fhircore/issues/864) for this. cc: @f-odhiambo

**Comment by ekigamba** [comment]
@shoaibmushtaq25 Cool, so I believe that this is a quick fix and might not serve the eventual scope of Quest and it goes against the spec. 
- The use of Quest for user-defined questionnaires and responses **might** not be harcoded to a specific display code
- It also goes against the spec since the spec requires that each code have the same display/text. We would want to follow the spec as much as we can so that we can maintain inter-operability and the FHIR standard. If our API/database was to be used by another app/web/system other than the Quest app, then we will have to apply the same rules/logic in all those systems so that they can display the Questionnaire displays the correct way. This will initially affect the Quest web and any other person who decides to use the API directly.

Can you create an issue to follow-up on this? What do you think?

**Comment by shoaibmushtaq25** [comment]
@ekigamba , yeah, It make sense. I think , we need to discuss more about the proper solution that should meet the FHIR specs. 
I will create a separate follow up on this and we can discuss the details over there.

**Comment by shoaibmushtaq25** [comment]
@ekigamba , I have created a follow up issue #895 , Please have a look and edit it if it needs any modifications in the description or I missed something in it.
